#write a program to store seven fruits in alist entered by user
fruits=[]
f1=input("Enter your fruits name:" )
fruits.append(f1)
f2=input("Enter your fruits name:" )
fruits.append(f2)
f3=input("Enter your fruits name:" )
fruits.append(f3)
f4=input("Enter your fruits name:" )
fruits.append(f4)
f5=input("Enter your fruits name:" )
fruits.append(f5)
f6=input("Enter your fruits name:" )
fruits.append(f6)
f7=input("Enter your fruits name:" )
fruits.append(f7)
print(fruits)