#write a program to input eight numbers form the user and display at the unique number (once)
s=set()
n= input("enter the number")
s.add(int(n))
n= input("enter the number")
s.add(int(n))
n= input("enter the number")
s.add(int(n))
n= input("enter the number")
s.add(int(n))
n= input("enter the number")
s.add(int(n))
n= input("enter the number")
s.add(int(n))
n= input("enter the number")
s.add(int(n))
print(s)